# Service
apiVersion: v1
kind: Service
metadata:
  name: merchant-portal-ui-service
  namespace: msp
spec:
  selector:
    app: merchant-portal-ui
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer


